-- GENERATED by scripts/gen-seed.ts — do not edit by hand.
-- Source: src/data/pictograms.ts, src/data/boards.ts, src/lib/localAuth.ts.
-- Regenerate with: npm run seed:gen

-- GoTrue's sign-in path reads these token columns with NOT NULL semantics
-- even though the schema allows NULL. Explicit empty strings avoid a 500.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-0000000000a1', 'authenticated', 'authenticated',
  'stub@talrum.local', crypt('stub-password-dev-only', gen_salt('bf')),
  now(), now(), now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{}'::jsonb, false,
  '', '', '', ''
);

insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (
  gen_random_uuid(), '00000000-0000-0000-0000-0000000000a1', '00000000-0000-0000-0000-0000000000a1',
  jsonb_build_object('sub', '00000000-0000-0000-0000-0000000000a1', 'email', 'stub@talrum.local'),
  'email', now(), now(), now()
);

insert into kids (id, owner_id, name) values ('liam', '00000000-0000-0000-0000-0000000000a1', 'Liam');

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('wakeup', '00000000-0000-0000-0000-0000000000a1', 'Wake up', 'illus', 'sun', 'oklch(90% 0.06 90)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('bed', '00000000-0000-0000-0000-0000000000a1', 'Out of bed', 'illus', 'bed', 'oklch(88% 0.05 300)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('brush', '00000000-0000-0000-0000-0000000000a1', 'Brush teeth', 'illus', 'tooth', 'oklch(88% 0.05 240)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('dress', '00000000-0000-0000-0000-0000000000a1', 'Get dressed', 'illus', 'shirt', 'oklch(88% 0.05 45)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('shoes', '00000000-0000-0000-0000-0000000000a1', 'Shoes on', 'illus', 'shoe', 'oklch(88% 0.05 155)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('breakfast', '00000000-0000-0000-0000-0000000000a1', 'Breakfast', 'illus', 'bowl', 'oklch(88% 0.05 45)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('apple', '00000000-0000-0000-0000-0000000000a1', 'Apple', 'illus', 'apple', 'oklch(88% 0.05 20)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('cup', '00000000-0000-0000-0000-0000000000a1', 'Drink', 'illus', 'cup', 'oklch(88% 0.05 240)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('bag', '00000000-0000-0000-0000-0000000000a1', 'Backpack', 'illus', 'bag', 'oklch(88% 0.05 155)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('car', '00000000-0000-0000-0000-0000000000a1', 'Go to car', 'illus', 'car', 'oklch(88% 0.05 300)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('park', '00000000-0000-0000-0000-0000000000a1', 'Park', 'photo', null, null, null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('store', '00000000-0000-0000-0000-0000000000a1', 'Supermarket', 'photo', null, null, null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('zoo', '00000000-0000-0000-0000-0000000000a1', 'Zoo', 'photo', null, null, null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('play', '00000000-0000-0000-0000-0000000000a1', 'Playground', 'photo', null, null, null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('book', '00000000-0000-0000-0000-0000000000a1', 'Story time', 'illus', 'book', 'oklch(88% 0.05 300)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('bath', '00000000-0000-0000-0000-0000000000a1', 'Bath', 'illus', 'bath', 'oklch(88% 0.05 240)', null, null);

insert into pictograms
  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values
  ('heart', '00000000-0000-0000-0000-0000000000a1', 'Love', 'illus', 'heart', 'oklch(88% 0.05 20)', null, null);

insert into boards
  (id, owner_id, kid_id, name, kind, labels_visible, voice_mode, step_ids, accent, accent_ink) values
  ('morning', '00000000-0000-0000-0000-0000000000a1', 'liam', 'Morning routine', 'sequence', true, 'tts', array['wakeup', 'brush', 'dress', 'breakfast', 'bag', 'car']::text[], 'peach', 'peach-ink');

insert into boards
  (id, owner_id, kid_id, name, kind, labels_visible, voice_mode, step_ids, accent, accent_ink) values
  ('afterschool', '00000000-0000-0000-0000-0000000000a1', 'liam', 'After school', 'sequence', true, 'tts', array['bag', 'apple', 'book', 'bath']::text[], 'sage', 'sage-ink');

insert into boards
  (id, owner_id, kid_id, name, kind, labels_visible, voice_mode, step_ids, accent, accent_ink) values
  ('weekend', '00000000-0000-0000-0000-0000000000a1', 'liam', 'Saturday — where to?', 'choice', true, 'tts', array['park', 'store', 'zoo']::text[], 'sky', 'sky-ink');

insert into boards
  (id, owner_id, kid_id, name, kind, labels_visible, voice_mode, step_ids, accent, accent_ink) values
  ('bedtime', '00000000-0000-0000-0000-0000000000a1', 'liam', 'Bedtime', 'sequence', true, 'tts', array['bath', 'book', 'cup', 'bed']::text[], 'lavender', 'lavender-ink');
