/**
 * Generates supabase/seed.sql from the single source of truth in src/data.
 *
 * Run with:
 *   npm run seed:gen
 *
 * Do not hand-edit supabase/seed.sql — the check:seed CI step will diff it.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SEED_BOARDS } from '../src/data/boards.ts';
import { PICTOGRAMS } from '../src/data/pictograms.ts';
import { LOCAL_KID_ID, LOCAL_PARENT_ID } from '../src/lib/localAuth.ts';
import type { Board, Pictogram } from '../src/types/domain.ts';

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`;

const nullable = (value: string | undefined): string =>
  value === undefined ? 'null' : quote(value);

const textArray = (values: readonly string[]): string =>
  `array[${values.map(quote).join(', ')}]::text[]`;

const STUB_EMAIL = 'stub@talrum.local';
const STUB_PASSWORD = 'stub-password-dev-only';

/**
 * Seeds a Supabase auth.users row with a fixed uuid so the Phase 2 client
 * (signing in with email + password) lands on the same owner_id the seed rows
 * carry, satisfying RLS without changing policies. Phase 3 deletes this block
 * and real users sign up through the UI — policies are untouched.
 */
const authUserRows = (): string =>
  [
    `-- GoTrue's sign-in path reads these token columns with NOT NULL semantics`,
    `-- even though the schema allows NULL. Explicit empty strings avoid a 500.`,
    `insert into auth.users (`,
    `  instance_id, id, aud, role, email, encrypted_password,`,
    `  email_confirmed_at, created_at, updated_at,`,
    `  raw_app_meta_data, raw_user_meta_data, is_super_admin,`,
    `  confirmation_token, recovery_token, email_change_token_new, email_change`,
    `) values (`,
    `  '00000000-0000-0000-0000-000000000000',`,
    `  ${quote(LOCAL_PARENT_ID)}, 'authenticated', 'authenticated',`,
    `  ${quote(STUB_EMAIL)}, crypt(${quote(STUB_PASSWORD)}, gen_salt('bf')),`,
    `  now(), now(), now(),`,
    `  '{"provider":"email","providers":["email"]}'::jsonb,`,
    `  '{}'::jsonb, false,`,
    `  '', '', '', ''`,
    `);`,
    ``,
    `insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)`,
    `values (`,
    `  gen_random_uuid(), ${quote(LOCAL_PARENT_ID)}, ${quote(LOCAL_PARENT_ID)},`,
    `  jsonb_build_object('sub', ${quote(LOCAL_PARENT_ID)}, 'email', ${quote(STUB_EMAIL)}),`,
    `  'email', now(), now(), now()`,
    `);`,
  ].join('\n');

const kidRow = (): string =>
  `insert into kids (id, owner_id, name) values (${quote(LOCAL_KID_ID)}, ${quote(LOCAL_PARENT_ID)}, ${quote('Liam')});`;

const pictogramRow = (p: Pictogram): string => {
  const glyph = p.style === 'illus' ? quote(p.glyph) : 'null';
  const tint = p.style === 'illus' ? quote(p.tint) : 'null';
  const imagePath = p.style === 'photo' ? nullable(p.imagePath) : 'null';
  return [
    'insert into pictograms',
    '  (id, owner_id, label, style, glyph, tint, image_path, audio_path) values',
    `  (${quote(p.id)}, ${quote(LOCAL_PARENT_ID)}, ${quote(p.label)}, ${quote(p.style)}, ${glyph}, ${tint}, ${imagePath}, ${nullable(p.audioPath)});`,
  ].join('\n');
};

const boardRow = (b: Board): string =>
  [
    'insert into boards',
    '  (id, owner_id, kid_id, name, kind, labels_visible, voice_mode, step_ids, kid_reorderable, accent, accent_ink) values',
    `  (${quote(b.id)}, ${quote(LOCAL_PARENT_ID)}, ${quote(b.kidId)}, ${quote(b.name)}, ${quote(b.kind)}, ${String(b.labelsVisible)}, ${quote(b.voiceMode)}, ${textArray(b.stepIds)}, ${String(b.kidReorderable)}, ${quote(b.accent)}, ${quote(b.accentInk)});`,
  ].join('\n');

const banner = [
  '-- GENERATED by scripts/gen-seed.ts — do not edit by hand.',
  '-- Source: src/data/pictograms.ts, src/data/boards.ts, src/lib/localAuth.ts.',
  '-- Regenerate with: npm run seed:gen',
  '',
].join('\n');

const pictograms = Object.values(PICTOGRAMS).map(pictogramRow).join('\n\n');
const boards = SEED_BOARDS.map(boardRow).join('\n\n');

const sql = [banner, authUserRows(), '', kidRow(), '', pictograms, '', boards, ''].join('\n');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '..', 'supabase', 'seed.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql);

process.stdout.write(`wrote ${outPath}\n`);
