/**
 * Generates supabase/seed.sql from the single source of truth in src/data.
 *
 * Run with:
 *   npm run seed:gen
 *
 * Do not hand-edit supabase/seed.sql — the check:seed CI step will diff it.
 *
 * Emits template_pictograms and template_boards rows keyed by text slug.
 * handle_new_user() clones them into the signing-up user's tables on each
 * auth.users insert, minting fresh uuids and rewriting board step arrays
 * via a slug→uuid map.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SEED_BOARDS } from '../src/data/boards.ts';
import { PICTOGRAMS } from '../src/data/pictograms.ts';
import type { Board, Pictogram } from '../src/types/domain.ts';

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`;

const nullable = (value: string | undefined): string =>
  value === undefined ? 'null' : quote(value);

const textArray = (values: readonly string[]): string =>
  `array[${values.map(quote).join(', ')}]::text[]`;

const pictogramRow = (p: Pictogram): string => {
  const glyph = p.style === 'illus' ? quote(p.glyph) : 'null';
  const tint = p.style === 'illus' ? quote(p.tint) : 'null';
  const imagePath = p.style === 'photo' ? nullable(p.imagePath) : 'null';
  return [
    'insert into template_pictograms',
    '  (slug, label, style, glyph, tint, image_path, audio_path) values',
    `  (${quote(p.id)}, ${quote(p.label)}, ${quote(p.style)}, ${glyph}, ${tint}, ${imagePath}, ${nullable(p.audioPath)});`,
  ].join('\n');
};

const boardRow = (b: Board): string =>
  [
    'insert into template_boards',
    '  (slug, name, kind, labels_visible, voice_mode, step_slugs, kid_reorderable, accent, accent_ink) values',
    `  (${quote(b.id)}, ${quote(b.name)}, ${quote(b.kind)}, ${String(b.labelsVisible)}, ${quote(b.voiceMode)}, ${textArray(b.stepIds)}, ${String(b.kidReorderable)}, ${quote(b.accent)}, ${quote(b.accentInk)});`,
  ].join('\n');

const banner = [
  '-- GENERATED by scripts/gen-seed.ts — do not edit by hand.',
  '-- Source: src/data/pictograms.ts, src/data/boards.ts.',
  '-- Regenerate with: npm run seed:gen',
  '',
].join('\n');

const pictograms = Object.values(PICTOGRAMS).map(pictogramRow).join('\n\n');
const boards = SEED_BOARDS.map(boardRow).join('\n\n');

const sql = [banner, pictograms, '', boards, ''].join('\n');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '..', 'supabase', 'seed.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql);

process.stdout.write(`wrote ${outPath}\n`);
